-- drop all tables if they exist
DROP TABLE IF EXISTS PLAYER CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS COLOR CASCADE;
DROP TABLE IF EXISTS STATE CASCADE;


-- create all tables
CREATE TABLE STATE(
    STATE_ID SERIAL NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY (STATE_ID)
);

CREATE TABLE COLOR(
    COLOR_ID SERIAL NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY (COLOR_ID)
);

CREATE TABLE TEAM(
    TEAM_ID SERIAL NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    STATE_ID INT,
    COLOR_ID INT,
    WINS INT,
    LOSSES INT,
    PRIMARY KEY (TEAM_ID),
    FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PLAYER(
    PLAYER_ID SERIAL NOT NULL,
    TEAM_ID INT,
    UNIFORM_NUM INT,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL,
    MPG INT,
    PPG INT,
    RPG INT,
    APG INT,
    SPG float8,
    BPG float8,
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE
);